### ISSUE TITLE
Update selected rows from $scope

### ISSUE THREAD

**Issue by jonagoldman** [josebalius/ngReactGrid#11]
Using the checkbox cells example in http://josebalius.github.io/ngReactGrid/examples/customCells.html

I am trying to write a 'Select All' / 'Deselect All' buttons.

So in my Controller I have:

```js
$scope.selections = [];

$scope.grid = {
    columnDefs: [
        new ngReactGridCheckbox($scope.selections),
        ///...
    ],
    ///...
}

$scope.deselectAll = function () {
     $scope.selections = [];
};
```

but when I call deselectAll() the checkboxs are not updated (still checked)

How can I fix this?
How can I also select all checkboxes at once?
Thanks.

**Comment by josebalius** [comment]
@jonagoldman You have probably moved on with this, so closing.
