### ISSUE TITLE
Support Autosize height Grid

### ISSUE THREAD

**Issue by dungvu-qe** [josebalius/ngReactGrid#57]
In version 0.7, there's is no way to set height of grid when resize controls, it always set a fixed height when init grid only(default = 400px). Could you support a param like "height" = "auto", "*" or "100%" to make grid filled in the Div placeholder?

Thanks for support, dev.

**Comment by josebalius** [comment]
I'll allow for the param to be set, not sure about 100% of the div, css can get tricky.

**Comment by bastienJS** [comment]
I can just upvote this request by dungvu-qe. @josebalius just do it like ui-grid is doing it.
https://github.com/angular-ui/ng-grid/blob/master/misc/tutorial/213_auto_resizing.ngdoc

**Comment by Lafriks** [comment]
+1
