### ISSUE TITLE
Support auto show/hide Horizontal scrolling bar

### ISSUE THREAD

**Issue by dungvu-qe** [josebalius/ngReactGrid#58]
In version 0.7, we only set or not set show Horizontal scrolling bar only. If we have 2-3 columns or 20 columns, the grid will shows Horizontal bar when set this.
Could you create a param to support auto show/hide Horizontal scrolling bar if all the columns size larger 
than the placeholder.
And when you finish feature "Resizeable columns", this params is becoming most wanted request. :)
Thank for support,

**Comment by josebalius** [comment]
@dungvu-qe good point. I'll see what I can do with some free time coming up.
