### ISSUE TITLE
Error using search input

### ISSUE THREAD

**Issue by tdekoekkoek** [josebalius/ngReactGrid#61]
I'm getting the following error typing into the search box:  Uncaught RangeError: Maximum call stack size exceeded.   It occurs in i.deepSearch

**Comment by josebalius** [comment]
@tdekoekkoek can you provide me with some sample code and a sample dataset?

**Comment by tdekoekkoek** [comment]
Sorry for not getting back.  I haven't been on that project for several days.  I think it might have to do with nested recursive properties from Breeze. Will try to get you something soon.  thanks.

**Comment by josebalius** [comment]
@tdekoekkoek I see you opened this again, any updates?

**Comment by tdekoekkoek** [comment]
Sorry,

I don't remember reopening it.  I don't think I intended to.  I haven't
dealt with the grid in a while, but hopefully soon I can take another look.

Regards,

Trevor

On Wed, Apr 22, 2015 at 8:06 PM, Jose Garcia notifications@github.com
wrote:

> @tdekoekkoek https://github.com/tdekoekkoek I see you opened this
> again, any updates?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/josebalius/ngReactGrid/issues/61#issuecomment-95371947
> .

## 

Trevor de Koekkoek
http://sincere.ly/tdekoekkoek

**Comment by josebalius** [comment]
Np, thank you.
