### ISSUE TITLE
Periodic loading of grid data causes control to fallback on 1st page

### ISSUE THREAD

**Issue by sohanboost** [josebalius/ngReactGrid#70]
I am using ng-react-grid with page-wise display. I need to reload the grid data periodically, for which I am using $timout of angular. I am able to reload the grid data periodically, but if before the page gets refreshed, control is on second page and page refresh happens, control falls back on first page. It seems that when page refresh happens, layout is re-drawn. Is there any way by which data gets refreshed without re-drawing layout?

**Comment by josebalius** [comment]
Hmm @sohanboost could you post some sample code for me to look at?

**Comment by sohanboost** [comment]
Apologies for misconception. Its not an issue hence closing it.
