### ISSUE TITLE
HTML content inside cell not rendering as HTML

### ISSUE THREAD

**Issue by Progdom** [josebalius/ngReactGrid#71]
Hi I'm attempting to embed HTML content into several cells but I am having issues with it escaping the html into entities. How can this be accomplished? 
![image](https://cloud.githubusercontent.com/assets/2650030/7281763/716b4b64-e8e0-11e4-8ed2-a28de983b2ba.png)

**Comment by josebalius** [comment]
@Progdom take a look at http://josebalius.github.io/ngReactGrid/examples/customCells.html you will have to either write Javascript in the form of `React.DOM.a({href: "#"}, 'C')` and return them in your cell renderer or use JSX instead.
