### ISSUE TITLE
is there any way to refresh the resultant data obtained from grid search?

### ISSUE THREAD

**Issue by sohanboost** [josebalius/ngReactGrid#73]
I am using ng-react-grid in such a way that its data get refresh every 1sec. If I search within grid using "Grid Search" control, I am getting the desired resultant data but this resultant data isn't getting refreshed. Is there any way to achieve this?

**Comment by josebalius** [comment]
@sohanboost i don't think this is supported at the moment. We would have to expose an API for you apply local data without resetting the grid state.

There are other ways you could do it but it would result in a hack, such as reading the DOM value of the search box and doing the filtering yourself and then setting the data, again not ideal.

**Comment by sohanboost** [comment]
ok. Thanks.
